version: '3.4'
services:
    api:
        build: ./api
        restart: always
        ports:
            - 5000:5000
        env_file:
            - .env
    ui:
        build: ./web_ui
        restart: always
        ports:
            - 5001:5001
        env_file:
            - .env